### ISSUE TITLE
Tech stack decisions

### ISSUE THREAD

**Issue by rahul-sivalenka** [TheMathematicians/lists#1]
Decide on tech stack to be used for the app

**Comment by rahul-sivalenka** [comment]
@StevensonNelli and me had a discussion about this.

The idea is to use React as front-end, Firebase as backend and GitHub Pages for hosting the app. Firebase also provides hosting options. Have to compare the pricing model.

#### Why React?
* Wanted to learn it. That's the one and only reason for me.

#### Why GitHub Pages?
* It's free upto a certain limit. It seems to allow higher bandwidth ([refer](https://help.github.com/en/articles/what-is-github-pages#usage-limits)) than Firebase ([refer](https://firebase.google.com/pricing/?gclid=Cj0KCQjwgezoBRDNARIsAGzEfe6lE1pIFgGiGaKBWXNpcXY7gVy3hqWbTMDo5XGoB8sJbpqJ7CyTpfQaAoxIEALw_wcB)). 
* `create-react-app` is easily setup to host on GitHub Pages ([refer](https://github.com/gitname/react-gh-pages)).
* It seems like `react boilerplate` also can be configured to support gh-pages. (see [this link](https://github.com/react-boilerplate/react-boilerplate/issues/1735)).
* There seems to be a problem if we use react router which can be overcome by some hacky way noted in [here](https://itnext.io/so-you-want-to-host-your-single-age-react-app-on-github-pages-a826ab01e48).
* If this seems too much, we can always go for static site generator alternative like Gatsby, but I don't know if some of the dynamic actions work on static sites. Have to check it out!

#### Why Firebase as backend?
* I don't see to much of database/backend needs other than storing links, lists and tags all of which can easily be stored in a NoSQL way. So Firebase seems to be easiest way.

**Comment by rahul-sivalenka** [comment]
Also thinking of adding
* [storybook](https://storybook.js.org/) to the app and
* unit tests to the components that we create

**Comment by StevensonNelli** [comment]
@rahul-sivalenka 
For unit testing will use [Jest](https://jestjs.io/) and [Enzyme](https://github.com/airbnb/enzyme).

- **Jest**  - It will provide you the basic testing API. ( like Jasmine/Karma )
- **Enzyme** - It will provide you an additional utility API to query the React DOM and Components. ( like Angular Test suite )

**Comment by rahul-sivalenka** [comment]
Needs to be a PWA as this app is intended to work on both mobile and desktop. Which means the app should be responsive.

**Comment by rahul-sivalenka** [comment]
Closing the ticket as the tech stack is decided
